version: '3.7'

services:
  api:
    container_name: mfcc-api
    build: 
      context: ./api
    restart: always
    ports:
      - "7071:7071"
    environment:
      - HOST=0.0.0.0
      - PORT=7071
      
    
